import { useState } from "react"
import { Link } from "react-router-dom"
import { Key } from "lucide-react"
import ApiKeyModal, { getStoredApiKey } from "./ApiKeyModal"

export default function Header() {
  const [isModalOpen, setIsModalOpen] = useState(false)
  const hasApiKey = !!getStoredApiKey()

  return (
    <>
      <header className="px-6 py-4 border-b border-gray-100 bg-sky-100">
        <div className="flex items-center justify-between max-w-6xl mx-auto">
          <div className="flex-1" />
          <Link
            to="/"
            className="hover:text-gray-700 transition-colors flex flex-col items-center"
          >
            <h1 className="text-xl font-bold text-gray-900">Layered Books</h1>
            <span className="text-sm text-gray-500">
              Navigate a book using a nested bullet point outline generated by AI.
            </span>
          </Link>
          <div className="flex-1 flex justify-end">
            <button
              onClick={() => setIsModalOpen(true)}
              className={`flex items-center gap-1.5 px-3 py-1.5 text-sm rounded-md cursor-pointer transition-colors font-medium ${
                hasApiKey
                  ? "bg-green-600 text-white hover:bg-green-700"
                  : "bg-black text-white hover:bg-gray-900"
              }`}
            >
              <Key className="h-4 w-4" />
              {hasApiKey ? "API Key Set" : "Set API Key"}
            </button>
          </div>
        </div>
      </header>
      <ApiKeyModal isOpen={isModalOpen} onClose={() => setIsModalOpen(false)} />
    </>
  )
}
